-- Remove abilities we don't use
DELETE FROM UnitAbilityModifiers WHERE UnitAbilityType = 'ABILITY_NAVAL_BOMBARD' OR UnitAbilityType = 'ABILITY_ATTACK_SUB_RAIDER' OR UnitAbilityType = 'ABILITY_ATTACK_SUB_SURFACE_WARSHIP' ;
DELETE FROM UnitAbilities WHERE UnitAbilityType = 'ABILITY_NAVAL_BOMBARD' OR UnitAbilityType = 'ABILITY_ATTACK_SUB_RAIDER' OR UnitAbilityType = 'ABILITY_ATTACK_SUB_SURFACE_WARSHIP' ;
DELETE FROM TypeTags WHERE Type = 'ABILITY_NAVAL_BOMBARD' OR Type = 'ABILITY_ATTACK_SUB_RAIDER' OR Type = 'ABILITY_ATTACK_SUB_SURFACE_WARSHIP' ;
DELETE FROM Types WHERE Type = 'ABILITY_NAVAL_BOMBARD' OR Type = 'ABILITY_ATTACK_SUB_RAIDER' OR Type = 'ABILITY_ATTACK_SUB_SURFACE_WARSHIP' ;


-- Remove these classes altogether (the units were be re-classed)
DELETE FROM TypeTags WHERE Tag = 'CLASS_ANTI_CAVALRY' OR Tag LIKE '%AUTOMATIC_GUN%' ;


-- Remove these old ability classes from units (the units were re-classed properly in GameDataLate.sql)
DELETE FROM TypeTags WHERE Type LIKE 'Unit%' AND (
Tag LIKE 'CLASS_AIRCRAFT'
OR Tag LIKE 'CLASS_AIR_ATTACK'
OR Tag LIKE 'CLASS_AIR_BOMBER'
OR Tag LIKE 'CLASS_AIR_FIGHTER'
OR Tag LIKE 'CLASS_ANTI_AIR'
OR Tag LIKE 'CLASS_ANTI_CAVALRY'
OR Tag LIKE 'CLASS_AUTOMATIC_GUN'
OR Tag LIKE 'CLASS_GIANT_DEATH_ROBOT'

OR Tag LIKE 'CLASS_HEAVY_CAVALRY'
OR Tag LIKE 'CLASS_LIGHT_CAVALRY'
OR Tag LIKE 'CLASS_LK_AUTOMATIC_GUN_ANTICAV'
OR Tag LIKE 'CLASS_LK_AUTOMATIC_GUN_CAV'
OR Tag LIKE 'CLASS_LK_AUTOMATIC_GUN_MELEE'
OR Tag LIKE 'CLASS_MARINE'
OR Tag LIKE 'CLASS_MELEE'
OR Tag LIKE 'CLASS_MONK'
OR Tag LIKE 'CLASS_NAVAL_BOMBARD'
OR Tag LIKE 'CLASS_NAVAL_CARRIER'
OR Tag LIKE 'CLASS_NAVAL_MELEE'
OR Tag LIKE 'CLASS_NAVAL_RAIDER'
OR Tag LIKE 'CLASS_NAVAL_RANGED'
OR Tag LIKE 'CLASS_RANGED'
OR Tag LIKE 'CLASS_RANGED_CAVALRY'

OR Tag LIKE 'CLASS_RECON'
OR Tag LIKE 'CLASS_SIEGE'
OR Tag LIKE 'CLASS_SUPPORT'
OR Tag LIKE 'CLASS_WARRIOR_MONK');