-- ('', '', 'en_US'),

INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES

('BW_LOC_MOD_HEAVY_INFANTRY_PHALANX_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_INFANTRY_PHALANX_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}', 'en_US'),
('BW_LOC_MOD_HEAVY_INFANTRY_OBLIQUE_ORDER_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_INFANTRY_OBLIQUE_ORDER_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}', 'en_US'),
('BW_LOC_MOD_HEAVY_INFANTRY_TESTUDO_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_INFANTRY_TESTUDO_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}', 'en_US'),

('BW_LOC_MOD_LIGHT_INFANTRY_SCREEN_PREVIEW', ' {BW_LOC_PROMOTION_LIGHT_INFANTRY_SCREEN_NAME} (enemy Light Inf)', 'en_US'),
('BW_LOC_MOD_LIGHT_INFANTRY_FLANK_GUARD_PREVIEW', ' {BW_LOC_PROMOTION_LIGHT_INFANTRY_FLANK_GUARD_NAME} (enemy Light Inf)', 'en_US'),

('BW_LOC_MOD_HEAVY_CAVALRY_MORALE_BOOST_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_CAVALRY_MORALE_BOOST_NAME} (adj Heavy Cavalry)', 'en_US'),
('BW_LOC_MOD_HEAVY_CAVALRY_HAMMER_AND_ANVIL_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_CAVALRY_HAMMER_AND_ANVIL_NAME} (enemy Heavy Cavalry)', 'en_US'),
('BW_LOC_MOD_HEAVY_CAVALRY_FLYING_WEDGE_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_CAVALRY_FLYING_WEDGE_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}', 'en_US'),
('BW_LOC_MOD_HEAVY_CAVALRY_FEINT_PREVIEW', ' {BW_LOC_PROMOTION_HEAVY_CAVALRY_FEINT_NAME} (enemy Heavy Cavalry)', 'en_US'),
('BW_LOC_MOD_HEAVY_CAVALRY_FEINT_MY_ATTACK_PREVIEW', ' Offset my {BW_LOC_PROMOTION_HEAVY_CAVALRY_FEINT_NAME}', 'en_US'),
('BW_LOC_MOD_HEAVY_CAVALRY_SHOCK_TACTICS_PREVIEW', '(Damaged unit [ICON_Strength] tripled due to {BW_LOC_PROMOTION_HEAVY_CAVALRY_SHOCK_TACTICS_NAME} on enemy Heavy Cavalry)', 'en_US'),

('BW_LOC_MOD_LIGHT_CAVALRY_ENVELOPE_PREVIEW', ' {BW_LOC_PROMOTION_LIGHT_CAVALRY_ENVELOPE_NAME} (enemy Light Cav)', 'en_US'),
('BW_LOC_MOD_LIGHT_CAVALRY_DUST_STORM_PREVIEW', ' {BW_LOC_PROMOTION_LIGHT_CAVALRY_DUST_STORM_NAME} (enemy Light Cav)', 'en_US'),
('BW_LOC_MOD_LIGHT_CAVALRY_PARTHIAN_SHOT_PREVIEW', ' {BW_LOC_PROMOTION_LIGHT_CAVALRY_PARTHIAN_SHOT_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}', 'en_US'),

('BW_LOC_MOD_RECON_TROOP_INTEL_PREVIEW', ' {BW_LOC_PROMOTION_RECON_TROOP_INTEL_NAME} (enemy Recon)', 'en_US'),




('BW_LOC_MOD_NAVAL_MELEE_NO_GALLEY_ATTACKING_SEA_PREVIEW', '+{1_Amount} Naval Melee attacking sea units', 'en_US'),
('BW_LOC_MOD_ATTACK_SUB_ATTACKING_SEA_PREVIEW', '+{1_Amount} Attack Sub attacking sea units', 'en_US'),
('BW_LOC_MOD_NAVAL_RANGED_ATTACKING_LAND_PREVIEW', '+{1_Amount} Naval Ranged attacking land units', 'en_US'),
('BW_LOC_MOD_NAVAL_RANGED_ATTACKING_SEA_PREVIEW', '{1_Amount} Naval Ranged attacking sea units', 'en_US'),
('BW_LOC_MOD_NAVAL_BOMBARD_ATTACKING_SEA_PREVIEW', '{1_Amount} Naval Bombard attacking sea units', 'en_US'),
('BW_LOC_MOD_NAVAL_RAIDER_ATTACKING_SEA_PREVIEW', '+{1_Amount} Naval Raider attacking sea units', 'en_US'),
('BW_LOC_MOD_NAVAL_RAIDER_ATTACKING_NAVAL_MELEE_PREVIEW', '+{1_Amount} Naval Raider attacking Naval Melee units', 'en_US')


;