-- ('', '', 'en_US'),

INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES

('BW_LOC_PROMOTION_CLASS_AIR_ATTACK_NAME', 'Air Ground-Attack', 'en_US'),
('BW_LOC_PROMOTION_CLASS_AIR_BOMBER_NAME', 'Air Bomber', 'en_US'),
('BW_LOC_PROMOTION_CLASS_AIR_FIGHTER_NAME', 'Air Fighter', 'en_US'),
('BW_LOC_PROMOTION_CLASS_ANTIAIR_NAME', 'Anti-Air', 'en_US'),
('BW_LOC_PROMOTION_CLASS_DEFENSIVE_GUN_NAME', 'Defensive Gun', 'en_US'),
('BW_LOC_PROMOTION_CLASS_ELEPHANT_NAME', 'War Elephant', 'en_US'),
('BW_LOC_PROMOTION_CLASS_GIANT_DEATH_ROBOT_NAME', 'Giant Death Robot', 'en_US'),
('BW_LOC_PROMOTION_CLASS_HEAVY_CAVALRY_NAME', 'Heavy Cavalry', 'en_US'),
('BW_LOC_PROMOTION_CLASS_HEAVY_INFANTRY_NAME', 'Heavy Infantry', 'en_US'),
('BW_LOC_PROMOTION_CLASS_LAND_RANGED_NAME', 'Land Ranged', 'en_US'),
('BW_LOC_PROMOTION_CLASS_LIGHT_CAVALRY_NAME', 'Light Cavalry', 'en_US'),
('BW_LOC_PROMOTION_CLASS_LIGHT_INFANTRY_NAME', 'Light Infantry', 'en_US'),
('BW_LOC_PROMOTION_CLASS_MARINE_NAME', 'Marine', 'en_US'),
('BW_LOC_PROMOTION_CLASS_MONK_NAME', 'Warrior Monk', 'en_US'),
('BW_LOC_PROMOTION_CLASS_NAVAL_BOMBARD_NAME', 'Naval Bombard', 'en_US'),
('BW_LOC_PROMOTION_CLASS_NAVAL_CARRIER_NAME', 'Carrier', 'en_US'),
('BW_LOC_PROMOTION_CLASS_NAVAL_MELEE_NAME', 'Naval Melee', 'en_US'),
('BW_LOC_PROMOTION_CLASS_NAVAL_RAIDER_NAME', 'Naval Raider', 'en_US'),
('BW_LOC_PROMOTION_CLASS_NAVAL_RANGED_NAME', 'Naval Ranged', 'en_US'),
('BW_LOC_PROMOTION_CLASS_RECON_NAME', 'Recon', 'en_US'),
('BW_LOC_PROMOTION_CLASS_SIEGE_NAME', 'Siege', 'en_US'),
('BW_LOC_PROMOTION_CLASS_SUPPORT_NAME', 'Support', 'en_US'),



-- Promotions used on multiple units
('BW_LOC_PROMOTION_DOUBLE_TIME_NAME', 'Double Time', 'en_US'),
('BW_LOC_PROMOTION_DOUBLE_TIME_DESCRIPTION', '+1 [ICON_Movement] movement', 'en_US'),

('BW_LOC_PROMOTION_SPYGLASS_NAME', 'Spyglass', 'en_US'),
('BW_LOC_PROMOTION_SPYGLASS_DESCRIPTION', '+1 sight range', 'en_US'),

('BW_LOC_PROMOTION_STEALTH_NAME', 'Stealth', 'en_US'),
('BW_LOC_PROMOTION_STEALTH_DESCRIPTION', 'Hidden from enemy units unless they are adjacent or have an ability to reveal stealth units', 'en_US'),

('BW_LOC_PROMOTION_ZONE_OF_CONTROL_NAME', 'Zone of Control', 'en_US'),
('BW_LOC_PROMOTION_ZONE_OF_CONTROL_DESCRIPTION', 'Exert a zone of control on adjacent enemy units', 'en_US'),

('BW_LOC_PROMOTION_ELUSIVE_NAME', 'Elusive', 'en_US'),
('BW_LOC_PROMOTION_ELUSIVE_DESCRIPTION', 'Ignore zones of control', 'en_US'),

('BW_LOC_PROMOTION_DOUBLE_STRIKE_NAME', 'Double Strike', 'en_US'),
('BW_LOC_PROMOTION_DOUBLE_STRIKE_DESCRIPTION', 'Can make 2 attacks in a turn', 'en_US'),

('BW_LOC_PROMOTION_IMPEL_NAME', 'Impel', 'en_US'),
('BW_LOC_PROMOTION_IMPEL_DESCRIPTION', 'Push back opponents when you attack and deal more damage to them than they do to you (and if they can''t retreat, they''ll take even more damage)', 'en_US'),

('BW_LOC_PROMOTION_HIT_AND_RUN_NAME', 'Hit and Run', 'en_US'),
('BW_LOC_PROMOTION_HIT_AND_RUN_DESCRIPTION', 'Move after attacking', 'en_US'),

('BW_LOC_PROMOTION_PRIORITY_TARGET_NAME', 'Priority Target', 'en_US'),
('BW_LOC_PROMOTION_PRIORITY_TARGET_DESCRIPTION', 'Acquire the ability to do a 65 damage attack to support (diamond icon) units, even when they share a tile with a front-line unit', 'en_US'),

('BW_LOC_PROMOTION_SURVIVALIST_NAME', 'Survivalist', 'en_US'),
('BW_LOC_PROMOTION_SURVIVALIST_DESCRIPTION', 'Heal after any action', 'en_US'),










('BW_LOC_PROMOTION_HEAVY_INFANTRY_PHALANX_NAME', 'Phalanx', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_INFANTRY_PHALANX_DESCRIPTION', '+10 [ICON_STRENGTH] Combat Strength on defense', 'en_US'),

('BW_LOC_PROMOTION_HEAVY_INFANTRY_SARISSA_NAME', 'Sarissa', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_INFANTRY_SARISSA_DESCRIPTION', '+5 [ICON_Strength] Combat Strength when attacking or defending land melee units (e.g. Heavy Infantry, Heavy Cavalry)', 'en_US'),

('BW_LOC_PROMOTION_HEAVY_INFANTRY_TESTUDO_NAME', 'Testudo', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_INFANTRY_TESTUDO_DESCRIPTION', '+10 [ICON_Strength] Combat Strength when defending ranged attacks', 'en_US'),


('BW_LOC_PROMOTION_LIGHT_INFANTRY_SCREEN_NAME', 'Screen', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_INFANTRY_SCREEN_DESCRIPTION', 'When next to a friendly land melee unit: adjacent enemies -7 [ICON_Strength] defense in land melee battles', 'en_US'),

('BW_LOC_PROMOTION_LIGHT_INFANTRY_FLANK_GUARD_NAME', 'Flank Guard', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_INFANTRY_FLANK_GUARD_DESCRIPTION', 'When next to a friendly land melee unit: adjacent enemies -7 [ICON_Strength] attack in land melee battles', 'en_US'),



/*
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_ATTACK__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_BOMBER__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_AIR_FIGHTER__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ANTIAIR__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_DEFENSIVE_GUN__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_ELEPHANT__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_GIANT_DEATH_ROBOT__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_HEAVY_CAVALRY__NAME', '', 'en_US'),
*/



/*
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LIGHT_CAVALRY__NAME', '', 'en_US'),
*/


/*
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MARINE__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_MONK__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_BOMBARD__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_CARRIER__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_MELEE__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RAIDER__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_NAVAL_RANGED__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_LAND_RANGED__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SIEGE__NAME', '', 'en_US'),

('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),
('BW_LOC_PROMOTION_SUPPORT__NAME', '', 'en_US'),

*/

('BW_LOC_PROMOTION_RECON_PATHFINDER_NAME', 'Pathfinder', 'en_US'),
('BW_LOC_PROMOTION_RECON_PATHFINDER_DESCRIPTION', 'Ignore terrain movement costs', 'en_US'),

('BW_LOC_PROMOTION_RECON_TROOP_INTEL_NAME', 'Troop Intel', 'en_US'),
('BW_LOC_PROMOTION_RECON_TROOP_INTEL_DESCRIPTION', 'Adjacent enemy units attack and defend with -3 [ICON_Strength] Combat Strength', 'en_US'),

('BW_LOC_PROMOTION_RECON_DISGUISE_NAME', 'Disguise', 'en_US'),
('BW_LOC_PROMOTION_RECON_DISGUISE_DESCRIPTION', 'Enter foreign territory (e.g. ignore closed borders)', 'en_US')

;