
INSERT OR REPLACE INTO Modifiers
(ModifierId,											ModifierType,											SubjectRequirementSetId)
VALUES	
('BW_MOD_MOVE_AFTER_ATTACK',							'MODIFIER_PLAYER_UNIT_ADJUST_ATTACK_AND_MOVE',			null),
('BW_MOD_+1_MOVEMENT'),
('BW_MOD_IRON_NERVES'),
('BW_MOD_EXTRA_ATTACK') ;
('BW_MOD_SEE_THROUGH_TERRAIN'),
('BW_MOD_REVEAL_STEALTH'),
('BW_MOD_IGNORE_TERRAIN_MOVEMENT'),
('BW_MOD_EXERT_ZOC'),
('BW_MOD_IGNORE_ZOC'),
('BW_MOD_ENTER_FOREIGN'),
('BW_MOD_STEALTH'),
('BW_MOD_HEAVY_INFANTRY_BULLDOZE'),
('BW_MOD_HEAVY_INFANTRY_PHALANX'),
('BW_MOD_HEAVY_INFANTRY_SARISSA'),
('BW_MOD_HEAVY_INFANTRY_TESTUDO'),
('BW_MOD_RECON_TROOP_INTEL') ;

INSERT OR REPLACE INTO ModifierArguments
(ModifierId,											Name,		Value)
VALUES
('BW_MOD_MOVE_AFTER_ATTACK',							'CanMove',	1),
('BW_MOD_+1_MOVEMENT'),
('BW_MOD_IRON_NERVES'),
('BW_MOD_EXTRA_ATTACK') ;
('BW_MOD_SEE_THROUGH_TERRAIN'),
('BW_MOD_REVEAL_STEALTH'),
('BW_MOD_IGNORE_TERRAIN_MOVEMENT'),
('BW_MOD_EXERT_ZOC'),
('BW_MOD_IGNORE_ZOC'),
('BW_MOD_ENTER_FOREIGN'),
('BW_MOD_STEALTH'),
('BW_MOD_HEAVY_INFANTRY_BULLDOZE'),
('BW_MOD_HEAVY_INFANTRY_PHALANX'),
('BW_MOD_HEAVY_INFANTRY_SARISSA'),
('BW_MOD_HEAVY_INFANTRY_TESTUDO'),
('BW_MOD_RECON_TROOP_INTEL') ;


/*

INSERT OR REPLACE INTO ModifierStrings
(ModifierId,											Context,	Text)
VALUES	











('BW_MOD_+8CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+49CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+10CS_ATTACK_LAND',							'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_LAND'),
('BW_MOD_-17CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+17CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_NAVAL_MELEE'),

('BW_MOD_+10CS_DEFEND',									'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_INFANTRY',	'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_INFANTRY',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_CAVALRY',	'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_CAVALRY',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+400PERCENT_SUPPORT_WHEN_NT_LAND_RANGED',		'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+400PERCENT_FLANK_WHEN_NT_LAND_RANGED',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_NORMAL_DAMAGE_DECREMENT',						'BW_DM_REDUCE_DAMAGE_DECREMENT_BY_PERCENT',				'BW_REQSET_NORMAL_DAMAGE_DECREMENT'),
('BW_MOD_TRIPLE_DAMAGE_DECREMENT',						'BW_DM_REDUCE_DAMAGE_DECREMENT_BY_PERCENT',				'BW_REQSET_TRIPLE_DAMAGE_DECREMENT')
;

/*

***** pushback should not apply to cities, encampments, and forts ******

('BW_MOD_PUSHBACK_RECON'			'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_RECON'),
('BW_MOD_PUSHBACK_LIGHT_INFANTRY'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_LIGHT_INFANTRY'),
('BW_MOD_PUSHBACK_HEAVY_INFANTRY'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_HEAVY_INFANTRY'),
('BW_MOD_PUSHBACK_LIGHT_CAVALRY'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_LIGHT_CAVALRY'),
('BW_MOD_PUSHBACK_HEAVY_CAVALRY'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_HEAVY_CAVALRY'),
('BW_MOD_PUSHBACK_LAND_RANGED'		'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_LAND_RANGED'),
('BW_MOD_PUSHBACK_SIEGE'			'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_SIEGE'),
('BW_MOD_PUSHBACK_MONK'				'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_MONK'),
('BW_MOD_PUSHBACK_SUPPORT'			'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_SUPPORT'),
('BW_MOD_PUSHBACK_NAVAL_BOMBARD'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_NAVAL_BOMBARD'),
('BW_MOD_PUSHBACK_NAVAL_CARRIER'	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_NAVAL_CARRIER'),
('BW_MOD_PUSHBACK_NAVAL_RANGED'		'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_NAVAL_RANGED'),
('BW_MOD_PUSHBACK_NAVAL_RAIDER'		'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',			'BW_REQSET_ATTACKING_NAVAL_RAIDER') ;


INSERT OR REPLACE INTO ModifierArguments
(ModifierId,											Name,		Value)
VALUES
('BW_MOD_MOVE_AFTER_ATTACK',							'CanMove',	1),
('BW_MOD_+8CS_ATTACK_SEA',								'Amount',	8),
('BW_MOD_+49CS_ATTACK_SEA',								'Amount',	49),
('BW_MOD_+10CS_ATTACK_LAND',							'Amount',	10),
('BW_MOD_-17CS_ATTACK_SEA',								'Amount',	-17),
('BW_MOD_+17CS_ATTACK_SEA',								'Amount',	17),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'Amount',	3),
('BW_MOD_+10CS_DEFEND',									'Amount',	10),
('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'Amount',	10),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'Amount',	10),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_INFANTRY',	'Percent',	900),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_INFANTRY',		'Percent',	900),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_CAVALRY',	'Percent',	900),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_CAVALRY',		'Percent',	900),
('BW_MOD_+400PERCENT_SUPPORT_WHEN_NT_LAND_RANGED',		'Percent',	400),
('BW_MOD_+400PERCENT_FLANK_WHEN_NT_LAND_RANGED',		'Percent',	400),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'Amount',	5),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'Amount',	5),
('BW_MOD_NORMAL_DAMAGE_DECREMENT',						'Amount',	90),
('BW_MOD_TRIPLE_DAMAGE_DECREMENT',						'Amount',	70)
;

('BW_MOD_PUSHBACK_RECON'			'ForceRetreat', 1),
('BW_MOD_PUSHBACK_LIGHT_INF'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_HEAVY_INF'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_LIGHT_CAV'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_HEAVY_CAV'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_LAND_RANGED'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_SIEGE'			'ForceRetreat', 1),
('BW_MOD_PUSHBACK_MONK'				'ForceRetreat', 1),
('BW_MOD_PUSHBACK_SUPPORT'			'ForceRetreat', 1),
('BW_MOD_PUSHBACK_NAVAL_BOMBARD'	'ForceRetreat', 1),
('BW_MOD_PUSHBACK_NAVAL_CARRIER'	'ForceRetreat', 1),
('BW_MOD_PUSHBACK_NAVAL_RANGED'		'ForceRetreat', 1),
('BW_MOD_PUSHBACK_NAVAL_RAIDER'		'ForceRetreat', 1)


INSERT OR REPLACE INTO ModifierStrings
(ModifierId,											Context,	Text)
VALUES	
('BW_MOD_+8CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+8CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+49CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+49CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+10CS_ATTACK_LAND',							'Preview',	'BW_LOC_MOD_+10CS_ATTACK_LAND_PREVIEW'),
('BW_MOD_-17CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_-17CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+17CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+17CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'Preview',	'BW_LOC_MOD_+3CS_ATTACK_NAVAL_MELEE_PREVIEW'),
('BW_MOD_+10CS_DEFEND',									'Preview',	'BW_LOC_MOD_+10CS_DEFEND'),
('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'Preview',	'BW_LOC_MOD_+10CS_ATTACK_HEAVY_INFANTRY'),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'Preview',	'BW_LOC_MOD_+10CS_ATTACK_ELEPHANT'),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'Preview',	'BW_LOC_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY'),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'Preview',	'BW_LOC_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY')
;

*/