INSERT OR REPLACE INTO Modifiers
(ModifierId,									ModifierType,											SubjectRequirementSetId)
VALUES	
('BW_MOD_MOVE_AFTER_ATTACK',					'MODIFIER_PLAYER_UNIT_ADJUST_ATTACK_AND_MOVE',			null),
('BW_MOD_+1_MOVEMENT',							'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT',					null),
('BW_MOD_+1_SIGHT',								'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT',					null),
('BW_MOD_IRON_NERVES',							'MODIFIER_PLAYER_UNIT_ADJUST_NO_REDUCTION_DAMAGE',		null),
('BW_MOD_EXTRA_ATTACK',							'MODIFIER_UNIT_ADJUST_NUM_ATTACKS',						null),
('BW_MOD_SEE_THROUGH_TERRAIN',					'MODIFIER_PLAYER_UNIT_ADJUST_SEE_THROUGH_FEATURES',		null),
('BW_MOD_STEALTH',								'MODIFIER_PLAYER_UNIT_ADJUST_HIDDEN_VISIBILITY',		null),
('BW_MOD_REVEAL_STEALTH',						'MODIFIER_PLAYER_UNIT_ADJUST_SEE_HIDDEN',				null),
('BW_MOD_MOVEMENT_IGNORE_TERRAIN',				'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_TERRAIN_COST',		null),
('BW_MOD_MOVEMENT_IGNORE_RIVER',				'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_RIVERS',			null),
('BW_MOD_EXERT_ZOC',							'MODIFIER_PLAYER_UNIT_ADJUST_EXERT_ZOC',				null),
('BW_MOD_IGNORE_ZOC',							'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_ZOC',				null),
('BW_MOD_ENTER_FOREIGN',						'MODIFIER_PLAYER_UNIT_ADJUST_ENTER_FOREIGN_LANDS',		null),
('BW_MOD_HEAVY_INFANTRY_PHALANX',				'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'DB_REQSET_DEFENDING'),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_INF',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_OPPONENT_IS_HEAVY_INFANTRY'),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_CAV',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_OPPONENT_IS_HEAVY_CAVALRY'),
('BW_MOD_HEAVY_INFANTRY_TESTUDO',				'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'DB_REQSET_DEFENDING_RANGED'),
('BW_MOD_RECON_TROOP_INTEL',					'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'DB_REQSET_ADJACENT_UNIT_AT_WAR')
;


INSERT OR REPLACE INTO ModifierArguments
(ModifierId,									Name,			Value)
VALUES
('BW_MOD_MOVE_AFTER_ATTACK',					'CanMove',		1),
('BW_MOD_+1_MOVEMENT',							'Amount',		1),
('BW_MOD_+1_SIGHT',								'Amount',		1),
('BW_MOD_IRON_NERVES',							'NoReduction',	1),
('BW_MOD_EXTRA_ATTACK',							'Amount',		1),
('BW_MOD_SEE_THROUGH_TERRAIN',					'CanSee',		1),
('BW_MOD_STEALTH',								'Hidden',		1),
('BW_MOD_REVEAL_STEALTH',						'SeeHidden',	1),
('BW_MOD_MOVEMENT_IGNORE_TERRAIN',				'Ignore',		1),	
('BW_MOD_MOVEMENT_IGNORE_TERRAIN',				'Type',			'ALL'),	
('BW_MOD_MOVEMENT_IGNORE_RIVER',				'Ignore',		1),	
('BW_MOD_ENTER_FOREIGN',						'Enter',		1),
('BW_MOD_HEAVY_INFANTRY_PHALANX',				'Amount',		10),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_INF',	'Amount',		5),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_CAV',	'Amount',		5),
('BW_MOD_HEAVY_INFANTRY_TESTUDO',				'Amount',		10),
('BW_MOD_RECON_TROOP_INTEL',					'Amount',		-3) ;


INSERT OR REPLACE INTO ModifierStrings
(ModifierId,									Context,	Text)
VALUES	
('BW_MOD_HEAVY_INFANTRY_PHALANX',				'Preview',	'+{1_Amount} {BW_LOC_PROMOTION_HEAVY_INFANTRY_PHALANX_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_INF',	'Preview',	'+{1_Amount} {BW_LOC_PROMOTION_HEAVY_INFANTRY_SARISSA_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
('BW_MOD_HEAVY_INFANTRY_SARISSA_VS_HEAVY_CAV',	'Preview',	'+{1_Amount} {BW_LOC_PROMOTION_HEAVY_INFANTRY_SARISSA_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
('BW_MOD_HEAVY_INFANTRY_TESTUDO',				'Preview',	'+{1_Amount} {BW_LOC_PROMOTION_HEAVY_INFANTRY_TESTUDO_NAME} {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
('BW_MOD_RECON_TROOP_INTEL',					'Preview',	'{1_Amount} {BW_LOC_PROMOTION_RECON_TROOP_INTEL_NAME}')
;


-- Pushback modifiers by unit class
-- TODO: ***** does pushback apply to forts? (also cities, encampments?) ******
INSERT OR REPLACE INTO Modifiers
(ModifierId,						ModifierType,							SubjectRequirementSetId)
SELECT	
'BW_MOD_PUSHBACK_' || ClassName,	'MODIFIER_UNIT_ADJUST_FORCE_RETREAT',	'BW_REQSET_ATTACKING_' || ClassName 
FROM BW_NewUnitClasses ;


INSERT OR REPLACE INTO ModifierArguments
(ModifierId,						Name,			Value)
SELECT	
'BW_MOD_PUSHBACK_' || ClassName,	'ForceRetreat',	1
FROM BW_NewUnitClasses ;


/*

('BW_MOD_+8CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+49CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+10CS_ATTACK_LAND',							'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_LAND'),
('BW_MOD_-17CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+17CS_ATTACK_SEA',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_NAVAL_MELEE'),

('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_INFANTRY',	'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_INFANTRY',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_CAVALRY',	'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_CAVALRY',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+400PERCENT_SUPPORT_WHEN_NT_LAND_RANGED',		'MODIFIER_PLAYER_UNIT_ADJUST_SUPPORT_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+400PERCENT_FLANK_WHEN_NT_LAND_RANGED',		'MODIFIER_PLAYER_UNIT_ADJUST_FLANKING_BONUS_MODIFIER',	'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',					'BW_REQSET_ATTACKING_SEA'),
('BW_MOD_NORMAL_DAMAGE_DECREMENT',						'BW_DM_REDUCE_DAMAGE_DECREMENT_BY_PERCENT',				'BW_REQSET_NORMAL_DAMAGE_DECREMENT'),
('BW_MOD_TRIPLE_DAMAGE_DECREMENT',						'BW_DM_REDUCE_DAMAGE_DECREMENT_BY_PERCENT',				'BW_REQSET_TRIPLE_DAMAGE_DECREMENT')
;

/*



INSERT OR REPLACE INTO ModifierArguments
(ModifierId,											Name,		Value)
VALUES
('BW_MOD_MOVE_AFTER_ATTACK',							'CanMove',	1),
('BW_MOD_+8CS_ATTACK_SEA',								'Amount',	8),
('BW_MOD_+49CS_ATTACK_SEA',								'Amount',	49),
('BW_MOD_+10CS_ATTACK_LAND',							'Amount',	10),
('BW_MOD_-17CS_ATTACK_SEA',								'Amount',	-17),
('BW_MOD_+17CS_ATTACK_SEA',								'Amount',	17),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'Amount',	3),
('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'Amount',	10),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'Amount',	10),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_INFANTRY',	'Percent',	900),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_INFANTRY',		'Percent',	900),
('BW_MOD_+900PERCENT_SUPPORT_WHEN_NT_LIGHT_CAVALRY',	'Percent',	900),
('BW_MOD_+900PERCENT_FLANK_WHEN_NT_LIGHT_CAVALRY',		'Percent',	900),
('BW_MOD_+400PERCENT_SUPPORT_WHEN_NT_LAND_RANGED',		'Percent',	400),
('BW_MOD_+400PERCENT_FLANK_WHEN_NT_LAND_RANGED',		'Percent',	400),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'Amount',	5),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'Amount',	5),
('BW_MOD_NORMAL_DAMAGE_DECREMENT',						'Amount',	90),
('BW_MOD_TRIPLE_DAMAGE_DECREMENT',						'Amount',	70)
;



INSERT OR REPLACE INTO ModifierStrings
(ModifierId,											Context,	Text)
VALUES	
('BW_MOD_+8CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+8CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+49CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+49CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+10CS_ATTACK_LAND',							'Preview',	'BW_LOC_MOD_+10CS_ATTACK_LAND_PREVIEW'),
('BW_MOD_-17CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_-17CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+17CS_ATTACK_SEA',								'Preview',	'BW_LOC_MOD_+17CS_ATTACK_SEA_PREVIEW'),
('BW_MOD_+3CS_ATTACK_NAVAL_MELEE',						'Preview',	'BW_LOC_MOD_+3CS_ATTACK_NAVAL_MELEE_PREVIEW'),
('BW_MOD_+10CS_ATTACK_HEAVY_INFANTRY',					'Preview',	'BW_LOC_MOD_+10CS_ATTACK_HEAVY_INFANTRY'),
('BW_MOD_+10CS_ATTACK_ELEPHANT',						'Preview',	'BW_LOC_MOD_+10CS_ATTACK_ELEPHANT'),
('BW_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY',	'Preview',	'BW_LOC_MOD_+5CS_TO_ADJACENT_ATTACKING_HEAVY_INFANTRY'),
('BW_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY',	'Preview',	'BW_LOC_MOD_+5CS_TO_ADJACENT_DEFENDING_HEAVY_INFANTRY')
;

*/