INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_IGNORE_TERRAIN_COST', 'BW_PROMOTION_CLASS_RECON') ;
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_IGNORE_CROSSING_RIVERS_COST', 'BW_PROMOTION_CLASS_RECON') ;
